service: code-jam

frameworkVersion: "2"

custom:
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    DOMAIN_SUFFIX: code-jam
  lambdaHashingVersion: 20201221
  profile: serverlessUser
  stage: dev
  region: ca-central-1
  httpApi:
    cors: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - lambda:*
      Resource: "*"

functions:
  load-everything:
    handler: lambdas/http-load-all.handler
    events:
      - http:
          path: /
          method: GET
          cors: true
  get-sentiment:
    handler: lambdas/http-get-sentiment.handler
    events:
      - http:
          path: /sentiment
          method: POST
          cors: true
  get-page-basics:
    handler: lambdas/http-get-page-basics.handler
    events:
      - http:
          path: /page-basics
          method: POST
          cors: true
  get-all-events:
    handler: lambdas/http-get-all-events.handler
    events:
      - http:
          path: /all-events
          method: POST
          cors: true
  get-all-posts:
    handler: lambdas/http-get-all-posts.handler
    events:
      - http:
          path: /all-posts
          method: POST
          cors: true
